### ISSUE TITLE
Should thread_local be used instead of static for retval and state0 in get_state() of file sofia-sip\libsofia-sip-ua\su\su_uniqueid.c?

### ISSUE THREAD

**Issue by DOL01** [jart/sofia-sip#1]
We are using this library and have seen crashes in this function when access retval->u64 for both read and write. I suspect the issue is caused by using static instead of thread_local for retval and state0 in get_state() of file sofia-sip\libsofia-sip-ua\su\su_uniqueid.c as described below:

If thread A initialized/updated retval and before retval->u64 is used for read or write later on, some other thread B preempty this thread and called this function and updated retval and called pthread_key_delete(), this will free the memory pointed by retval. When thread A resumes the processing to access the memory pointed by retval, the access violation will happen since the memory has been freed by thread A.

Could any one confirm if my understanding is correct? Thanks.

Dongning

**Comment by jart** [comment]
This is a mirror repository. The best place to reach out might be http://sofia-sip.sourceforge.net/ but unfortunately it seems like Sofia-SIP isn't maintained by Nokia anymore. Sorry I couldn't be any help!
